"""empty message

Revision ID: f2280d67ef7f
Revises: 
Create Date: 2025-05-10 07:15:01.738762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2280d67ef7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('program_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('program_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
